name: Publish to NPM

on:
  push:
    branches: ["main"]

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        shell: bash

      - name: Lint
        run: pnpm lint

      - name: Build packages
        run: pnpm build

      - name: Publish packages
        run: pnpm publish --access public
